version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "4000:4000"
    env_file:
      - .env
      - db.env
    restart: on-failure
    volumes:
      - /app/node_modules
    command: ["node", "dist/main.js"]
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    env_file:
      - db.env
    restart: on-failure
    volumes:
      - ./data:/var/lib/postgresql/data